// Package mcu provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package mcu

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for ComputerType.
const (
	Mcu   ComputerType = "mcu"
	Pc    ComputerType = "pc"
	Skull ComputerType = "skull"
)

// Computer defines model for Computer.
type Computer struct {
	Id     int    `json:"id"`
	Ip     string `json:"ip"`
	Name   string `json:"name"`
	Online bool   `json:"online"`

	// Type Type of computer or device
	Type ComputerType `json:"type"`

	// Uptime Uptime in human-readable format
	Uptime string `json:"uptime"`
}

// ComputerType Type of computer or device
type ComputerType string

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/2xTwY7bIBD9FTTt0XXsbFW1vq1yqCJVag7tqdoDweNktjBQGEeNovz7Cpx4N8peDIY3",
	"j8fjzQmMd8EzsiToTpDMHp0u05V3YRSMeR6iDxiFsOxQn7/4X7tgEbq2AjkGhA6IBXcY4VwBhRsMtN+W",
	"dfvla93WbQMVDD46LbkkHD7DTJAkEu9yPWuHtww/h4EMqs3qPbhnS3xbIHHEGbn13qLmDJ1WTtBjMpGC",
	"kGfo4NcxoPKDMpdbKx9VjwcyCBUgjw66PxAMVODMCBWkv6O18FS9EVh275SNQci9c+Dvsq6I1X50mj9F",
	"1L3eWlQXa94yP/Rqub8nP1cQ8d9IEfusjvor5GJfeYVZwWzS00zkt89oBM6ZiXjw9yofN+ssSDnNeke8",
	"U1pZSjI5xYxGsH/1bDIs1VkHSZF+TZFa8wFZfDyqx80aKjhgTNMZbd3UTXnEgKwD5QvXTf0AFQQt+xK5",
	"xfWM8rdDyUPOpM5C1z108B1lNYOyMyl4TlNil02TB+NZkEutDsGSKdWL55R1XMNfEi7oSuHHiAN08GHx",
	"2iaLS48s5gaZQwU6Rn2c/Lz18cds2lVhxqTROR2Pk3ilrb3ZP59fAgAA//83lGhgngMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
